---
title: "Introduction to Oral Opioids"
author: "Ankona Banerjee & Erik Stricker "
date: "`r Sys.Date()`"
output: rmarkdown::html_document

vignette: >
  %\VignetteIndexEntry{OralOpioids}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

------------

## Description
Provides details such as Morphine Equivalent Dose (MED), brand name and
opioid content which are calculated of all oral opioids authorized for
sale by Health Canada based on their Drug Identification Number (DIN)
or FDA based on their Product ID for Opioids authorized for sale in
Canadian or US markets.
For US Opioids, MEDs are calculated using Von Korff et al. (2008) and information
obtained from FDA's daily National Drug Code Directory [/drug/ndc] download
MEDs are calculated based on recommendations by Canadian Institute for
Health Information (CIHI) and information obtained from Health Canada’s
Drug Product Database’s monthly data dump for Canadian Opioids. 
Please note in no way should
output from this package be a substitute for medical advise.  
All medications should only be consumed on prescription from a licensed
healthcare provider

------------

## Functions
### Loading/updating the FDA dataset

```R
library(OralOpioids)
US_Opioid_Table <- load_Opioid_Table(country="US")
```

```R
head(US_Opioid_Table)
```
### Loading/updating the Health Canada dataset

```R
library(OralOpioids)
Canada_Opioid_Table <- load_Opioid_Table(country="Canada")
```

```R
head(Canada_Opioid_Table)
```


### Get the Morphine Equivalent Dose (MED) from FDA by using the Product ID

```R
MED("0093-0058",US_Table)
```


### Get the Morphine Equivalent Dose (MED) from Health Canada by using DIN

```R
MED(786535, Canada_Table)
```


### Get the Brand name from FDA by using the Product ID

```R
Brand("0093-0058", US_Table)
```

### Get the Brand name from Health Canada by using DIN

```R
Brand(786535, Canada_Table)
```

### Get the Opioid content from FDA by using the Product ID

```R
Opioid("0093-0058",US_Table)
```

### Get the Opioid content from Health Canada by using DIN

```R
Opioid(786535, Canada_Table)
```

### Get the Maximum number of units/millilitres of oral opioids allowed per day assuming a daily limit of 50 MED/day from FDA by using the Product ID

```R
MED_50("0093-0058",US_Table)
```

### Get the Maximum number of units/millilitres of oral opioids allowed per day assuming a daily limit of 50 MED/day from Health Canada by using DIN

```R
MED_50(786535, Canada_Table)
```

### Get the Maximum number of units/millilitres of oral opioids allowed per day assuming a daily limit of 90 MED/day from FDA by using the Product ID

```R
MED_90("0093-0058",US_Table)
```
### Get the Maximum number of units/millilitres of oral opioids allowed per day assuming a daily limit of 90 MED/day from Health Canada by using DIN

```R
MED_90(786535, Canada_Table)
```

